### ISSUE TITLE
Skip unmodified files

### ISSUE THREAD

**Issue by aistis-** [BrunoDeBarros/git-deploy-php#55]
Hello, it would be a nice feature to have unmodified files skipping. What do you thing, guys? I mean untracked files by git.

**Comment by pancakeapp** [comment]
The problem is that because they're untracked, you can't know if they've been modified. I guess one thing we could do is tweak the REVISION file so that it contains the hashes and filenames of all tracked files, so we can just use that to compare with what's being deployed, and skip unmodified files like that.

**Comment by aistis-** [comment]
Is it possible to get a remote file's checksum without download it? That way it could be simply compared with a local checksum and uploaded if different.

**Comment by pancakeapp** [comment]
No, that's why I said we can store the checksums in the REVISION file which is stored on the server, and then we download that file and use the checksums to compare. That would be easy to do.
